#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
if [ "$1" = "--xdebug" -o "$1" = "-xd" ] ; then
    shift 1
    set -- php -d zend_extension=xdebug.so "$@"
elif [ "${1#-}" != "$1" ]; then
	set -- php "$@"
fi

exec "$@"
